name: pi_mds
description: Dashboard Console para Sistema IoT ESP32 - Controle de Iluminação e Climatização
version: 1.0.0

environment:
  sdk: ^3.9.1

dependencies:
  http: ^1.1.0
  mysql1: ^0.20.0
  intl: ^0.19.0
  crypto: ^3.0.3
  io: ^1.0.4
  collection: ^1.18.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
